tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "colordiff"
brew "fish"
brew "jq"
brew "lesspipe"
brew "nkf"
brew "trash"
brew "source-highlight"
brew "telnet"
brew "the_silver_searcher"
brew "tree"
brew "anyenv"

cask "docker"
cask "1password"
cask "google-chrome"
cask "google-japanese-ime"
cask "spectacle"
cask "contexts"
cask "iterm2"
cask "scroll-reverser"
cask "visual-studio-code"
cask "dropbox"
cask "alfred"