"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[\$](bold green)'

[directory]
truncation_length = 10
truncate_to_repo = false

[aws]
format = '[($symbol\($profile\))(\[$duration\])]($style)'
symbol = '☁️'