# =============================
# Prefix key
# =============================
unbind C-b
set -g prefix C-t

# =============================
# General settings
# =============================
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g mouse on
set -g set-titles on
set -g set-titles-string '#S'

# 拡張キー（CSI u / KKP）のサポートを有効化
set -s extended-keys on

# Ghostty からの拡張キー入力を受け付ける機能フラグを付与
# (Ghostty の TERM が 'ghostty' または 'xterm-ghostty' 等になるためワイルドカードで指定)
set -as terminal-features 'ghostty*:extkeys'
set -as terminal-features 'xterm*:extkeys'
set -as terminal-features 'xterm-ghostty:RGB'

# Emacs に 256色+拡張機能対応のターミナルであることを伝える
# ※ "tmux-256color" がシステムにない場合は "screen-256color" にしてください
set -g default-terminal "tmux-256color"

# =============================
# Pane
# =============================
# split
bind | split-window -h -c "#{pane_current_path}"
bind '{' split-window -h -b -f
bind '}' split-window -h -f
bind - split-window -v -c "#{pane_current_path}"

# navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# =============================
# Cliboard & Copy mode
# =============================
set -s set-clipboard on

setw -g mode-keys emacs
# bind -T copy-mode-vi v send -X begin-selection
# bind -T copy-mode-vi C-v send -X rectangle-toggle
# bind -T copy-mode-vi y send -X copy-selection-and-cancel

# =============================
# Plugins
# =============================
setenv -g TMUX_PLUGIN_MANAGER_PATH '$HOME/.config/tmux/plugins/'
if "test ! -d ~/.config/tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && \
    ~/.config/tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

# 設定ファイルをリロードする
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

run '~/.config/tmux/plugins/tpm/tpm'