#!/usr/bin/env bash
set -euo pipefail

# TODO: 鍵が複数マッチしたときの挙動
# TODO: パスが .ssh になかった時用の設定

trap 'exit 1' 2

rawJson=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running")
instanceId=$(echo "$rawJson" | jq -r '.Reservations[].Instances[] | [ .InstanceId, (.Tags[]? | select(.Key == "Name")).Value ] | @sh' | sed "s/'//g" | peco | awk '{print $1}')
selectJson=$(echo "$rawJson" | jq ".Reservations[].Instances[] | select(.InstanceId == \"${instanceId}\")")

keyName=$(echo "$selectJson" | jq -r ".KeyName")
keyPath=$(find ~/.ssh/ -name "*${keyName}*.pem" | head -n 1)
if [ -z "$keyPath" ]; then
    echo "Cannot find key-pair" >&2
    exit 1
fi

publicIp=$(echo "$selectJson" | jq -r ".PublicDnsName")
if [ -z "$publicIp" ] || [ "$publicIp" = "null" ]; then
    echo "Instance does not have public IP" >&2
    exit 1
fi

platform=$(echo "$selectJson" | jq -r ".Platform")

if [ "$platform" = "windows" ]; then
    echo "Platform is Windows"
    {
        echo "auto connect:i:1"
        echo "full address:s:${publicIp}"
        echo "username:s:Administrator"
    } > "/tmp/${publicIp}.rdp"
    pass=$(aws ec2 get-password-data --instance-id "$instanceId" --priv-launch-key "$keyPath" --query 'PasswordData' --output text)
    if [ -z "$pass" ]; then
        echo "Cannot get password" >&2
        exit 1
    fi
    printf '%s' "$pass" | pbcopy
    open "/tmp/${publicIp}.rdp"
else
    echo "Platform is Linux"
    username=$(printf 'ec2-user\nubuntu\ncentos\n' | peco)
    ssh -i "$keyPath" "${username}@${publicIp}"
fi
