name: check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  nix-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix flake check
        run: nix flake check --impure
      - name: statix
        run: nix run nixpkgs#statix -- check .

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          ignore_paths: >-
            archives
            tmux/plugins
            .emacs.d
